# Brew
tap 'homebrew/bundle'
tap 'homebrew/completions'
tap 'homebrew/core'
tap 'homebrew/services'
tap 'homebrew/versions'

brew 'cmake'
brew 'readline'
brew 'ack'

brew 'bash'
brew 'bash-completion'
brew 'neovim'

brew 'git'
brew 'htop'
brew 'wget'
brew 'masscan'
brew 'nmap'
brew 'mitmproxy'
brew 'ssh-copy-id'

brew 'rbenv'
brew 'ruby-build'

brew 'nodenv'
brew 'node-build'
brew 'yarn'

brew 'fzf'
brew 'autojump'

brew 'phantomjs'

brew 'webp'
brew 'gifsicle'
brew 'ffmpeg', args: ['with-fontconfig', 'without-lame', 'without-qtkit', 'without-x264', 'without-xvid']
brew 'librsvg'
brew 'imagemagick', args: ['with-fontconfig', 'with-librsvg', 'with-webp']
brew 'libpng'
brew 'freetype'
brew 'fontconfig'
brew 'jpeg'
brew 'libtiff'

tap 'puma/puma'
brew 'puma/puma/puma-dev'

brew 'erlang'
brew 'elixir'

# MAS
brew 'mas'

mas 'Crazy Tomato', id: 1105814268

# CASK
tap 'caskroom/cask'
brew 'brew-cask-completion'

cask 'firefox'
cask 'google-chrome'
cask 'imageoptim'
cask 'iterm2'
cask 'pritunl'
cask 'dash'
cask 'postman'
cask 'spotify'
cask 'recordit'
